services:
    secit.imap:
        class: SecIT\ImapBundle\Service\Imap
        arguments: ["%secit.imap.connections%"]
        public: true

    SecIT\ImapBundle\Service\Imap:
        alias: secit.imap
        public: true

    SecIT\ImapBundle\Command\ValidateConnectionsCommand:
        public: false
        tags: [console.command]
        arguments: 
            - '@SecIT\ImapBundle\Service\Imap'
            - '@parameter_bag'